version: '0.2'
language: en
ignorePaths:
  - node_modules
  - .svelte-kit
  - build
  - .git
  - package-lock.json
  - cspell.config.yaml
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - .vscode
  - lefthook.yml
  - package.json
words:
  - AUTOINCREMENT
  - lefthook
  - libsql
  - linecap
  - linejoin
  - turso
  - TURSO
